# Generated by Django 4.1.3 on 2022-11-30 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_route', '0003_userroute_mode_of_travel_userroute_route_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='New', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request', to=settings.AUTH_USER_MODEL)),
                ('user_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request', to='user_route.userroute')),
            ],
        ),
    ]
