# Generated by Django 4.1.3 on 2022-11-30 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_route', '0003_userroute_mode_of_travel_userroute_route_type'),
        ('ride_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together={('user_route', 'created_by')},
        ),
    ]
