# Generated by Django 4.1.3 on 2022-11-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
