# Generated by Django 4.1.3 on 2022-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_route', '0002_userroute_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='mode_of_travel',
            field=models.CharField(choices=[('Car', 'Car'), ('BIKE', 'Bike'), ('SUV', 'Suv'), ('Others', 'Others')], default='Car', max_length=10),
        ),
        migrations.AddField(
            model_name='userroute',
            name='route_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=10),
        ),
    ]
